name: Makefile CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v3.1.0

      - name: Build project
        run: make
