name: Makefile CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install nasm
          brew install --cask maciasl

      - name: Download and install mtoc
        run: |
          curl -L -o ocmtoc.zip https://github.com/acidanthera/ocmtoc/releases/download/1.0.3/ocmtoc-1.0.3-RELEASE.zip
          unzip ocmtoc.zip
          sudo mv ./mtoc /usr/local/bin/mtoc

      - name: Build project
        run: make
