name: Makefile CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install nasm
          brew install --cask maciasl

      - name: Build and install mtoc
        run: |
          git clone https://github.com/acidanthera/ocmtoc
          cd ocmtoc
          ./make-mtoc
          sudo mv ./mtoc /usr/local/bin/mtoc
          cd ..

      - name: Build project
        run: make
